In [77]:
import  numpy as np
import pandas as pd

In [78]:
df=pd.read_csv('/content/data (1).csv')
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [80]:
df['date'] = pd.to_datetime(df['date']) #Convert date column to datetime

In [81]:
df['date'] = df['date'].dt.normalize() #Remove time part

In [82]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [83]:
df=df.drop('date', axis=1) #Drop original date column

In [84]:
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3        1340              0      1955          2005   
1     4          5        3370            280      1921             0   
2     0          4        1930              0      1966             0   
3     0          4        1000           1000      1963             0   
4     0          4        1140            800      1976          1992   

                     street       city  statezip country  year  month  day  
0      18810 Densmore Ave N  Shoreline  WA 98133     USA  2014      5    2  
1           709 W Blaine St    Seattle  WA 98119     USA  2014      5    2  
2  26206-26214 143rd Ave SE       Kent  WA 98042     USA  2014      5    2  
3           857 170th Pl NE   Bellevue  WA 98008     USA  2014      5    2  
4         9105 170th Ave NE    Redmond  WA 98052     USA  2014      5    2

In [85]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'street', 'city', 'statezip', 'country',
       'year', 'month', 'day'],
      dtype='object')

In [86]:
df['year'].value_counts()

year
2014    4600
Name: count, dtype: int64

In [87]:
df['month'].value_counts()

month
6    2179
5    1768
7     653
Name: count, dtype: int64

In [88]:
df=df.drop(['street','statezip'],axis=1)
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3        1340              0      1955          2005   
1     4          5        3370            280      1921             0   
2     0          4        1930              0      1966             0   
3     0          4        1000           1000      1963             0   
4     0          4        1140            800      1976          1992   

        city country  year  month  day  
0  Shoreline     USA  2014      5    2  
1    Seattle     USA  2014      5    2  
2       Kent     USA  2014      5    2  
3   Bellevue     USA  2014      5    2  
4    Redmond     USA  2014      5    2

In [89]:
len(df['city'].unique())

44

In [90]:
f={}
s=0
for i in df['city']:
  if i not in f:
    f[i]=s
    s=s+1
df['city']=df['city'].map(f).astype(int)

In [91]:
df['city'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [92]:
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  city  \
0     0          3        1340              0      1955          2005     0   
1     4          5        3370            280      1921             0     1   
2     0          4        1930              0      1966             0     2   
3     0          4        1000           1000      1963             0     3   
4     0          4        1140            800      1976          1992     4   

  country  year  month  day  
0     USA  2014      5    2  
1     USA  2014      5    2  
2     USA  2014      5    2  
3     USA  2014      5    2  
4     USA  2014      5    2

In [93]:
df['country']=df['country'].map({'USA':1}).astype(int)

In [94]:
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  city  \
0     0          3        1340              0      1955          2005     0   
1     4          5        3370            280      1921             0     1   
2     0          4        1930              0      1966             0     2   
3     0          4        1000           1000      1963             0     3   
4     0          4        1140            800      1976          1992     4   

   country  year  month  day  
0        1  2014      5    2  
1        1  2014      5    2  
2        1  2014      5    2  
3        1  2014      5    2  
4        1  2014      5    2

In [95]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'country', 'year', 'month', 'day'],
      dtype='object')

In [96]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

#train_test_split:


In [97]:
import sklearn

In [98]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [99]:
len(x_train),len(y_train)

(3680, 3680)

In [100]:
len(x_test),len(y_test)

(920, 920)

In [101]:
import warnings
warnings.filterwarnings('ignore')

In [102]:
X=x_train.values
X.shape[1]

17

In [103]:
y_train.values.shape

(3680,)

In [104]:
# Convert to numpy
X = x_train.values
y = y_train.values

n_features = X.shape[1]

m = []   # to store m1, m2, ..., m18

y_mean = np.mean(y)

for j in range(n_features):
    xj = X[:, j]
    xj_mean = np.mean(xj)

    numerator = np.sum((xj - xj_mean)**2 * (y - y_mean)**2)
    denominator = np.sum((xj - xj_mean) ** 2)

    mj = numerator / denominator
    m.append(mj)

m = np.array(m)
m

array([2.56668289e+11, 6.90811483e+11, 1.80249374e+12, 9.54118628e+10,
       1.44760620e+11, 3.14377348e+12, 7.46986563e+11, 1.62359551e+11,
       1.17437101e+12, 1.07823259e+12, 1.50875355e+11, 1.49598816e+11,
       2.62875502e+11,            nan,            nan, 1.42627076e+11,
       1.44881159e+11])

In [105]:
X_mean = np.mean(X, axis=0)   # mean of each column
c = y_mean - np.sum(m * X_mean)
c

np.float64(nan)

In [106]:
X_mean.shape

(17,)

In [107]:
zero_variance_cols = []
for j in range(n_features):
    if np.var(X[:, j]) == 0:
        zero_variance_cols.append(j)
zero_variance_cols

[13, 14]

In [108]:
# Find non-zero variance columns
valid_cols = []
for j in range(n_features):
    if np.var(X[:, j]) != 0:  #Variance tells us whether a column has changing values or not.
        valid_cols.append(j)
X_valid = X[:, valid_cols]

In [109]:
valid_cols

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16]

In [153]:
X_valid.shape

(3680, 15)

In [111]:
m = []
y_mean = np.mean(y)

for j in range(X_valid.shape[1]):
    xj = X_valid[:, j]
    xj_mean = np.mean(xj)

    numerator = np.sum((xj - xj_mean)**2 * (y - y_mean)**2)
    denominator = np.sum((xj - xj_mean) ** 2)

    mj = numerator / denominator
    m.append(mj)

m = np.array(m)
m

array([2.56668289e+11, 6.90811483e+11, 1.80249374e+12, 9.54118628e+10,
       1.44760620e+11, 3.14377348e+12, 7.46986563e+11, 1.62359551e+11,
       1.17437101e+12, 1.07823259e+12, 1.50875355e+11, 1.49598816e+11,
       2.62875502e+11, 1.42627076e+11, 1.44881159e+11])

In [112]:
X_mean = np.mean(X_valid, axis=0)

c = y_mean - np.sum(m * X_mean)
print(c)

-8146677460862716.0


#train data

In [113]:
X_train_valid = x_train.values[:, valid_cols]

y_train_pred = np.dot(X_train_valid, m) + c #(np.dot)-Multiply corresponding values and add them. [np.dot(x, m) = m1*x1 + m2*x2]

In [114]:
len(y_train_pred)

3680

In [115]:
print(X_train_valid.shape)
print(m.shape)
print(y_train_pred.shape)

(3680, 15)
(15,)
(3680,)


In [116]:
training_data = pd.DataFrame({'y_train':y_train.values.flatten(),'ans_train':y_train_pred })
training_data

y_train     ans_train
0     6.850000e+05  4.750976e+15
1     8.570000e+05  6.010617e+15
2     6.750000e+05  1.588149e+15
3     1.485000e+06  5.193597e+15
4     5.610000e+05 -9.341110e+14
...            ...           ...
3675  2.825089e+05 -3.856189e+15
3676  8.750000e+05  4.153592e+14
3677  2.900000e+05 -3.370687e+15
3678  6.000000e+05 -4.656793e+15
3679  4.750000e+05 -3.110163e+15

[3680 rows x 2 columns]

In [117]:
# mean square error
s = 0
for i in training_data.index:
  s  = s + (training_data['y_train'][i] - training_data['ans_train'][i])**2

print(f'Loss value from MSE : {s / len(training_data)}')

Loss value from MSE : 2.302011689586103e+31


In [118]:
# root mean square error
s = 0
for i in training_data.index:
  s  = s + (training_data['y_train'][i] - training_data['ans_train'][i])**2

print(f'Loss value from RMSE : {np.sqrt(s / len(training_data))}')

Loss value from RMSE : 4797928396283236.0


In [119]:
# Absolute mean square error
s = 0
for i in training_data.index:
    s = s + abs(training_data['y_train'][i] - training_data['ans_train'][i])

print(f'Loss value from AMSE : {s / len(training_data)}')


Loss value from AMSE : 2923955984237339.5


In [120]:
# Train Accuracy

numerator = 0
denominator = 0
for i in training_data.index:
  numerator  = numerator + (training_data['y_train'][i] - training_data['ans_train'][i])**2
  denominator = denominator + (training_data['y_train'][i] - training_data['y_train'].mean())**2


print(f'Train Accuracy By r2_score formula : {1 - (numerator) / denominator}')

Train Accuracy By r2_score formula : -1.6201549691931355e+20


In [121]:
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error,r2_score
mean_squared_error(y_train,y_train_pred)

2.3020116895860983e+31

In [122]:
root_mean_squared_error(y_train,y_train_pred)

4797928396283232.0

In [123]:
mean_absolute_error(y_train,y_train_pred)

2923955984237336.5

In [124]:
r2_score(y_train,y_train_pred)

-1.620154969193131e+20

#test data

In [125]:
X_test_valid = x_test.values[:, valid_cols]

y_test_pred = np.dot(X_test_valid, m) + c

In [126]:
print(X_test_valid.shape)
print(m.shape)
print(y_test_pred.shape)

(920, 15)
(15,)
(920,)


In [127]:
testing_data = pd.DataFrame({'y_test':y_test.values.flatten(), 'ans_test':y_test_pred})
testing_data

y_test      ans_test
0      544000.0 -3.361929e+15
1           0.0 -1.189857e+15
2     1712500.0  1.682919e+15
3      365000.0 -6.474468e+14
4      275000.0 -1.652910e+15
..          ...           ...
915    750000.0 -1.704941e+15
916    230000.0 -1.222611e+15
917  26590000.0 -3.584984e+15
918    687000.0  1.784663e+14
919    289659.0 -4.239926e+14

[920 rows x 2 columns]

In [128]:
# mean square error
s = 0
for i in testing_data.index:
  s  = s + (testing_data['y_test'][i] - testing_data['ans_test'][i])**2

print(f'Loss value from MSE : {s / len(testing_data)}')

Loss value from MSE : 2.7243043016663005e+31


In [129]:
# root mean square error
s = 0
for i in testing_data.index:
  s  = s + (testing_data['y_test'][i] - testing_data['ans_test'][i])**2

print(f'Loss value from RMSE : {np.sqrt(s / len(testing_data))}')

Loss value from RMSE : 5219486853768578.0


In [130]:
# Absolute mean square error
s = 0
for i in testing_data.index:
    s = s + abs(testing_data['y_test'][i] - testing_data['ans_test'][i])

print(f'Loss value from AMSE : {s / len(testing_data)}')


Loss value from AMSE : 2988082564848954.0


In [131]:
# Test Accuracy

numerator = 0
denominator = 0
for i in testing_data.index:
  numerator  = numerator + (testing_data['y_test'][i] - testing_data['ans_test'][i])**2
  denominator = denominator + (testing_data['y_test'][i] - testing_data['y_test'].mean())**2


print(f'Test Accuracy By r2_score formula : {1 - (numerator) / denominator}')

Test Accuracy By r2_score formula : -2.6712889918632452e+19


In [132]:
mean_squared_error(y_test,y_test_pred)

2.724304301666299e+31

In [133]:
root_mean_squared_error(y_test,y_test_pred)

5219486853768576.0

In [134]:
mean_absolute_error(y_test,y_test_pred)

2988082564848953.0

In [135]:
r2_score(y_test,y_test_pred)

-2.671288991863243e+19

#checking

In [136]:
l=[3.0	,1.50,	1340,	7912,	1.5	,0	,0	,3	,1340,	0	,1955,	2005	,	2014	,5,	2]
len(l)

15

In [137]:
q = np.dot(l, m) + c
q

np.float64(-2274928491389537.0)

#saving model

In [154]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_valid,y_train)

LinearRegression()

In [156]:
a=reg.predict([[3.0	,1.50,	1340,	7912,	1.5	,0	,0	,3	,1340,	0	,1955,	2005	,	2014	,5,	2]])
a

array([-6077484.97272948])

In [157]:
import pickle

In [165]:
with open('MINI_HOUSE.plk','wb') as f:
  pickle.dump(reg,f)

In [167]:
with open('/content/MINI_HOUSE.plk','rb') as f:
  z=pickle.load(f)

In [168]:
z.predict([[3.0	,1.50,	1340,	7912,	1.5	,0	,0	,3	,1340,	0	,1955,	2005	,	2014	,5,	2]])

array([-6077484.97272948])